// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGN8ffziyx9nl5lWdfG7kt2IGE-xey_e8',
    appId: '1:1043848910209:web:2363abccdf1fc7f4598480',
    messagingSenderId: '1043848910209',
    projectId: 'fir-login-2f91e',
    authDomain: 'fir-login-2f91e.firebaseapp.com',
    storageBucket: 'fir-login-2f91e.appspot.com',
    measurementId: 'G-XH3BCWWYX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Z4mzpyQ91TnKKBOTN1GHvFrlTb8N5wA',
    appId: '1:1043848910209:android:6a38a16dc1dc2940598480',
    messagingSenderId: '1043848910209',
    projectId: 'fir-login-2f91e',
    storageBucket: 'fir-login-2f91e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc6HVE_Ks4e4TsyyqkEvczpUkQgBIFtJ4',
    appId: '1:1043848910209:ios:3cc7b372ce7b8f72598480',
    messagingSenderId: '1043848910209',
    projectId: 'fir-login-2f91e',
    storageBucket: 'fir-login-2f91e.appspot.com',
    iosClientId: '1043848910209-o69lb7va4t4su5gmedr7r2p8uv29mibu.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiFlutter',
  );
}
